export const preciosEnvio = {
  CABA: 5500,
  ZONA1: 6300,
  ZONA2: 8000,
  ZONA3: 10300
};

export const mapeoLocalidades = [
  { nombre: "Capital Federal", zona: "CABA" },
  { nombre: "Lanus", zona: "ZONA1" },
  { nombre: "Lomas de Zamora", zona: "ZONA1" },
  { nombre: "Avellaneda", zona: "ZONA1" },
  { nombre: "Matanza Norte", zona: "ZONA1" },
  { nombre: "Moron", zona: "ZONA1" },
  { nombre: "Ituzaingo", zona: "ZONA1" },
  { nombre: "Hurlingham", zona: "ZONA1" },
  { nombre: "3 de Febrero", zona: "ZONA1" },
  { nombre: "San Martin", zona: "ZONA1" },
  { nombre: "Vicente Lopez", zona: "ZONA1" },
  { nombre: "San Isidro", zona: "ZONA1" },
  { nombre: "San Fernando", zona: "ZONA1" },
  { nombre: "Quilmes", zona: "ZONA2" },
  { nombre: "Berazategui", zona: "ZONA2" },
  { nombre: "Florencio Varela", zona: "ZONA2" },
  { nombre: "Almirante Brown", zona: "ZONA2" },
  { nombre: "Esteban Echeverria", zona: "ZONA2" },
  { nombre: "Ezeiza", zona: "ZONA2" },
  { nombre: "Matanza Sur", zona: "ZONA2" },
  { nombre: "Merlo", zona: "ZONA2" },
  { nombre: "Moreno", zona: "ZONA2" },
  { nombre: "Jose C Paz", zona: "ZONA2" },
  { nombre: "San Miguel", zona: "ZONA2" },
  { nombre: "Malvinas Argentinas", zona: "ZONA2" },
  { nombre: "Nordelta", zona: "ZONA2" },
  { nombre: "Tigre", zona: "ZONA2" },
  { nombre: "La Plata", zona: "ZONA3" },
  { nombre: "San Vicente", zona: "ZONA3" },
  { nombre: "Guernica", zona: "ZONA3" },
  { nombre: "Alejandro Korn", zona: "ZONA3" },
  { nombre: "Cañuelas", zona: "ZONA3" },
  { nombre: "Marcos Paz", zona: "ZONA3" },
  { nombre: "General Rodriguez", zona: "ZONA3" },
  { nombre: "Lujan", zona: "ZONA3" },
  { nombre: "Pilar", zona: "ZONA3" },
  { nombre: "Derqui", zona: "ZONA3" },
  { nombre: "Garin", zona: "ZONA3" },
  { nombre: "Escobar", zona: "ZONA3" },
  { nombre: "Zarate", zona: "ZONA3" },
  { nombre: "Campana", zona: "ZONA3" }
];